language: ruby
rvm:
  - 2.3.0
addons:
  code_climate:
    repo_token: 92e95f195eb9ae99c668029ce248d1afa227d9c49da059977fcc608533b88be5
addons:
  postgresql: "9.4"
before_script:
  - bundle install
  - bundle exec rake db:create
  - bundle exec rake db:migrate
script: bundle exec rspec
