redisdata:
  image: 'busybox'
  volumes:
    - /data

redis:
  image: 'redis:3-alpine'
  command: 'redis-server --appendonly yes'
  volumes_from:
    - redisdata

app:
  build: '.'
  command: 'bundle exec rails s -b 0.0.0.0'
  environment:
    - 'REDIS_URL=redis://redis:6379'
    - 'SECRET_TOKEN=twinkle-secret-token'
    - 'RESQUE_WEB_HTTP_BASIC_AUTH_USER=admin'
    - 'RESQUE_WEB_HTTP_BASIC_AUTH_PASSWORD=admin'
  ports:
    - '3000:3000'
  volumes:
    - '.:/app'
  links:
    - redis

worker:
  build: '.'
  command: 'bundle exec rake resque:work --trace'
  environment:
    - 'QUEUE=*'
    - 'REDIS_URL=redis://redis:6379'
  volumes:
    - '.:/app'
  links:
    - redis
