pgdata:
  image: 'busybox'
  volumes:
    - /data
  environment:
    - POSTGRES_PASSWORD=mypass

pg:
  image: 'postgres:9.4'
  volumes_from:
    - pgdata

redisdata:
  image: 'busybox'
  volumes:
    - /data

redis:
  image: 'redis:3-alpine'
  command: 'redis-server --appendonly yes'
  volumes_from:
    - redisdata

app:
  build: '.'
  dockerfile: Dockerfile.development
  command: 'bundle exec rails s -b 0.0.0.0'
  environment:
    - DATABASE_URL=postgres://postgres:mypass@pg/twinkle
    - REDIS_URL=redis://redis:6379
    - RESQUE_WEB_HTTP_BASIC_AUTH_USER=admin
    - RESQUE_WEB_HTTP_BASIC_AUTH_PASSWORD=admin
  ports:
    - '3000:3000'
  volumes:
    - '.:/app'
  links:
    - pg
    - redis

worker:
  build: '.'
  dockerfile: Dockerfile.development
  command: 'bundle exec rake resque:work --trace'
  environment:
    - 'QUEUE=*'
    - DATABASE_URL=postgres://postgres:mypass@pg/twinkle
    - REDIS_URL=redis://redis:6379
  volumes:
    - '.:/app'
  links:
    - pg
    - redis
