default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  # DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] + '_test' %>

production:
  <<: *default
